### ISSUE TITLE
codegen-generated code does not compile for non-raw but zero-length messages

### ISSUE THREAD

**Issue by dmezh** [opencan/opencan#61]
reproducer:

```yaml
nodes:
- PCH:
    messages:
    - Status:
        cycletime: 20
        id: 0x40
        signals: []
```
